import { test, expect} from '@playwright/test';
test.describe('Codegen Example', () => {
    test ('Simple Google Search Example', async ({page}) => {
        await test.step('Navigate to google.com', async () => {

            // Following lines generated by Playwright Codegen tool
            await page.goto('https://www.google.com');
            await page.getByRole('combobox', { name: 'Search' }).click();
            await page.getByRole('combobox', { name: 'Search' }).fill('test');
            await page.getByRole('button', { name: 'Google Search' }).first().click();
        });

    });
});